config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  root to: "questions#index"
  resources :questions, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    collection do
      get 'search'
    end
    resources :answers, only: [:new, :create, :edit, :update, :destroy]
  end
  resources :informations, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to   :user
  belongs_to   :question

  validates :text, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to  :user
  has_many    :answers,  dependent: :destroy

  with_options presence: true do
    validates :title
    validates :content
  end

  def self.search(search)
    if search != ''
      Question.where('title LIKE(?) ', "%#{search}%")
    else
      Question.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  validates :phone_number, presence: true, format: { with: /\A^(0{1}\d{9,10})$\z/ }

  has_many  :questions
  has_many  :answers

  def self.guest
    find_or_create_by!(email: 'guest@example.com', phone_number: '09033338888', nickname: 'guest') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :set_answer, only: [:edit, :update, :destroy]

  def new
    @answer = Answer.new(question_id: @question_id)
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to question_path(@answer.question)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to question_path(@question.id)
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to root_path
  end

  private

  def answer_params
    params.require(:answer).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :phone_number])
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.page(params[:page]).per(10).order('updated_at DESC')
    @posts = Question.all.count
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @answer = Answer.new
    @answers = @question.answers.includes(:user)
    @best = Answer.select(:question_id)
  end

  def search
    @questions = Question.search(params[:keyword])
    @posts = @questions.count
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to question_path
    else
      render :edit
    end
  end

  def destroy
    @question.destroy if current_user.id == @question.user_id
    redirect_to root_path
  end

  private

  def question_params
    params.require(:question).permit(:title, :content, :best_answer_id).merge(user_id: current_user.id)
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def move_to_index
    unless redirect_to action: :index
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    redirect_to root_path if resources.email == 'guest@example.com'
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/informations_helper.rb
module InformationsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/edit.html.erb
<div class="contents-row">
<h1 class="title">
   <%= link_to "戻る", root_path, class:"back" %>
 </h1>
<div class="container-in">
<div class="box">
   <%= form_with(model:@answer,url: question_answer_path, local: true) do |f|%>
  <div class="field">
    <%= f.label :text, "回答", class: "answer-content" %><br />
    <%= f.text_area :text, class: "answer-content", size:"40x5"%>
  </div>

  <div class="question-btn-contents">
     <%= f.submit "編集する", class:"btn" %>
  </div>  
  </div>
  </div>
  <% end %>
  

app/views/answers/new.html.erb
  <div class="contents-row">
  <h1 class="title">
   <%= link_to "戻る", root_path, class:"back" %>
 </h1>
  <div class="container-in">
  <div class="box">
  <%= form_with(model:@answer,url: question_answers_path, local: true) do |f|%>
  <div class="field">
    <%= f.label :text, "回答", class: "answer-content" %><br />
    <%= f.text_area :text, class: "answer-content", size:"40x5"%>
  </div>

  <div class="question-btn-contents">
     <%= f.submit "回答する", class:"btn" %> 
  </div>  
  <% end %>
  </div>
 </div>
 </div>

app/views/informations/index.html.erb
<div class="contents-row">
<h1 class="title">
   <%= link_to "戻る", root_path, class:"back" %>
</h1>
<div class="drug-information">

<h1 class="information-title">小児の薬ののませ方・使い方 </h1>
<div class="drug-powder">
<button id="powder" class="btn">粉薬</button>
<ul id="powder-list">
<li>
通常、粉薬は水と一緒に飲みますが、小さなお子さまの場合には粉の感じや味が苦手で飲まないことがあります。なので飲ませ方の工夫をご紹介します。
</li>
 ・スポイトやスプーンを利用する。<br>
 １．粉薬が入っているところにスポイトで水を少しずつたらしながら混ぜる。<br>
 ２．スポイトで吸い上げて飲ませる。<br>
 <li>
 ・お薬団子を作る<br>
 １．１回分の粉薬をお皿にあけ、１〜２滴の水を落として、団子状に固めます。
 ２．完成したお薬団子を白湯で飲ませるか、上あごやほほの内側に塗りつけてください。
 </li>
 <b>してはいけないこと</b>
 <li>
 ・ご飯と一緒に飲ませない。<br>
 苦い薬がこどもが飲みにくいからといって、食事と一緒に飲ませないようにしてください。場合によっては食事が嫌いになり食べなくなってしまうことがあります。
 </li>
<li>
  ・抗生物質などの苦いお薬などは、飲み合わせの相性が悪いものがある。<br>
  苦い粉薬などは苦味を抑えるためにコーティングが施されていますが、酸性の飲みのもの（スポーツ飲料やりんごジュース）に混ぜると苦味が増してしまう可能性があります。
</li>
</ul>
<div class="drug-tablet">
<button id="tablet" class="btn">錠剤</button>
<ul id="tablet-list">
<li>
錠剤によっては大きさが違ったりすることもあって飲ませにくいことがあったりします。まずは焦らないことが大切です。ここでは飲ませ方の工夫について紹介します。
</li>
<li>
・粉薬に変更する<br>
薬の種類によっては粉薬があるものもあります。錠剤が飲めないときには薬剤師や医師の先生に相談してみるといいかも知れません。
</li>
<li>
・服薬補助ゼリーを使用する。<br>
服薬補助ゼリーは錠剤にも使用することが可能です。使ってみるとよいでしょう。
</li>
<li>
・飲む練習をする<br>
小さなラムネや砕いたチョコレートを使用して飲み込む練習をするのも良いでしょう
</li>
<li>
<b>してはいけないこと</b>
</li>
<li>
・錠剤を砕いて飲ませる。<br>
薬の種類によっては砕かないほうがいいものあります。自己判断で砕いたりせず、薬剤師や医師の先生に相談するようにしましょう。
</li>
</div>
</div>
</div>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
 </div>
 <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MedicalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<div class="contents-row">
<h1 class="title">
 <%= link_to "戻る", :back, class:"back" %>
</h1>
<div class="container-in">
<div class="box">
<%= form_with(model: @question, local: true) do |f|%>
  <div class="field">
    <%= f.label :title, "題名",class: "questions-title" %><br />
    <%= f.text_field :title, class: "questions-title", size:"40×5" %>
  </div>

  <div class="field">
    <%= f.label :content, "質問内容", class: "content" %><br />
    <%= f.text_area :content, class: "content", size:"40x5" %>
  </div>

  <div class="question-btn-contents">
     <%= f.submit "編集する", class:"btn" %>
     </div> 
  </div>
<% end %>
</div>
</div>

app/views/questions/index.html.erb
<div class="wrapper">
<%= render "shared/header" %>
<body>
   
    <div class="mask">
    
    <div class="question-lists">質問一覧
    <div class="question-counts">
    <%= "現在の質問数:#{@posts}"%>
    <%= form_with(url: search_questions_path, local:true, method: :get, class: "search-form") do |form| %>
   <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
   <%= form.submit "検索", class: "btn" %>
   <% end %>
    </div>
     <% @questions.each do |question|%>
      <ul class="list">
         <%= link_to  "#{question.title}", question_path(question.id)  %>
      <li class="question-list">
      質問者:<%= question.user.nickname %>
      </li>
      <li class="question-list">
           質問した日
         <%=l question.created_at %>
      </li>
      </ul>
    <% end %>
     <%= paginate @questions %>
     </div>
  
    
</body>
<%= render "shared/footer"%>
</div>
</div>

app/views/questions/new.html.erb
<div class="contents-row">
<h1 class="title">
   <%= link_to "戻る", root_path, class:"back" %>
</h1>
  <div class="container-in">
  <div class="box">
<%= form_with(model: @question, local: true) do |f|%>
<%= render 'layouts/error_messages', model: f.object %>
<h2>質問投稿</h2>
  <div class="field">
    <%= f.label :title, "題名" %><br />
    <%= f.text_field :title, placeholder:"題名", class: "questions-title" %>
  </div>

  <div class="field">
    <%= f.label :content, "質問内容" %><br />
    <%= f.text_area :content, placeholder:"質問内容", class: "content"%>
  </div>

  <div class="question-btn-contents">
     <%= f.submit "質問する", class:"btn" %>
  </div>
  </div>
 </div>
</div>
<% end %>

app/views/questions/search.html.erb
<div class="wrapper">
<%= render "shared/header" %>
<body>
   <div class="question-lists">検索結果
    <div class="question-counts">
    <%= "検索数：#{@posts}" %>
    <%= form_with(url: search_questions_path, local:true, method: :get, class: "search-form") do |form| %>
   <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
   <%= form.submit "検索", class: "btn" %>
   <% end %>
   </div>
   <div class="contents row">
    <% @questions.each do |question|  %>
      <li class="list">
         <%= link_to  "#{question.title}", question_path(question.id)  %>
      <h1 class="question-list">
           質問した日
         <%=l question.created_at %>
      </h1>
     <% end %>
    </div>
    </body> 
    </div>
    <%= render "shared/footer"%>

app/views/questions/show.html.erb
<div class="contents-row">
  
   <h1 class="title">
     <%= link_to "お薬相談室", root_path, class:'title'%>
   </h1>
    
  <div class="container"> 
 <div class="question-wrapper">

 
 <h1 class="question-title">
  <%= @question.title%>
 </h1>

 <p class="body-text">
  質問内容：<%= @question.content %>
  </p>
  <p class="user-nickname">
   質問者:<%= @question.user.nickname %>
   </p>

 <p class="question-manage">
 
  <% if user_signed_in? %>
      <% if current_user.id === @question.user_id%>
      <%= link_to edit_question_path do %>
      <button class="btn">編集する</button>
      <% end  %>
      <%= link_to question_path, method: :delete do %>
      <button class="btn">削除する</button>
      <% end %>
  
     <% else %>
     <%= link_to new_question_answer_path(@question.id) do %>
     <button class="btn">回答する</button>
     <% end %>
   
   <% end  %>
  <% end %>
  </p>
  
  </div>
  </div>




  <div class="answer-lists">回答一覧
  <% @answers.each do |answer| %>
  <li class="answer-list">
  <%= answer.user.nickname%> :
   <%= answer.text %>
   </li>
   <li class="answer-list-name">
   <% if user_signed_in? %>
     <% if current_user.id === answer.user_id %>
     <%= link_to edit_question_answer_path(@question, answer) do %>
     <button class="btn">編集する</button>
     <% end %>
     <%= link_to question_answer_path(@question, answer), method: :delete do %>
     <button class="btn">削除する</button>
     <% end %>
      <% elsif current_user.id === @question.user_id %>
     
     <div class="action"> 
      <button class="btn">解決</button>
       </div> 
       </div> 
    
       <% end %>
      <% end %>
   </li>
   <% end %>

   </div>
  
  

app/views/shared/_footer.html.erb
<footer class="top-page-fotter">
  <div class="footer-nav">
   <ul class="footer-list">
     <li>
   </ul>
   <%= link_to '子供の薬ののませ方', informations_path, class: 'information' %>
   </div>

app/views/shared/_header.html.erb
   <header class='top-page-header'>
   <h1 class="header-title">
     <%= link_to "お薬相談室", root_path, class:"header-title" %>
   </h1>   
      <div class='header-nav'>
       <ul class='list-right'> 
        <% if user_signed_in? %>
        <div class="name">
        <%= "ようこそ#{current_user.nickname}さん"  %>
        </div>
         <li><%=link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'log-out'%></li>
         <li><%=link_to '質問する', new_question_path, class: 'question'%>
        <% else %> 
         <li><%=link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class:'guest-log-in'%>
         <li><%=link_to '新規登録',  new_user_registration_path, class:'sign-in'%></li>
         <li><%=link_to 'ログイン',  new_user_session_path, class:'log-in'%></li>
        <% end %> 
        
       </ul>
       </div>
   </header>